spring.application.name=ps

spring.datasource.url=jdbc:postgresql://localhost:5432/AirTravelDB
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true