spring.application.name=first

spring.datasource.url=jdbc:postgresql://localhost:5432/Project1
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true