spring.application.name=oauth2

spring.datasource.url=jdbc:postgresql://localhost:5432/oAuthDB2
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.client.registration.google.client-id=your-google-client-id
spring.security.oauth2.client.registration.google.client-secret=your-google-client-secret

jwt.secret=yourSecretKey123
jwt.expiration=3600000
jwt.refreshDuration = 604800000