spring.application.name=second

spring.datasource.url=jdbc:postgresql://localhost:5432/restaurantDB
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=c2155a59c9b0b8
spring.mail.password=028021800a7ef2

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true